version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=1
    depends_on:
      db:
        condition: service_healthy  # Wait for db to be healthy
    networks:
      - foodnet  # Specify the network

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: fooddb
      POSTGRES_USER: fooddb_user
      POSTGRES_PASSWORD: fooddb_password
    ports:
      - "5432:5432"
    networks:
      - foodnet  # Specify the network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fooddb_user"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  foodnet:  # Define the network