# Generated by Django 4.2.17 on 2025-01-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTruck',
            fields=[
                ('location_id', models.IntegerField(primary_key=True, serialize=False)),
                ('applicant', models.CharField(max_length=255)),
                ('facility_type', models.CharField(max_length=50)),
                ('cnn', models.IntegerField()),
                ('location_description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('block_lot', models.CharField(max_length=20)),
                ('block', models.CharField(max_length=10)),
                ('lot', models.CharField(max_length=10)),
                ('permit', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=50)),
                ('food_items', models.TextField(blank=True, null=True)),
                ('x_coordinate', models.FloatField()),
                ('y_coordinate', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('schedule_url', models.URLField(max_length=500)),
                ('days_hours', models.CharField(blank=True, max_length=255, null=True)),
                ('noi_sent', models.DateTimeField(blank=True, null=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('received_date', models.DateField()),
                ('prior_permit', models.BooleanField()),
                ('expiration_date', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('fire_prevention_district', models.IntegerField()),
                ('police_district', models.IntegerField()),
                ('supervisor_district', models.IntegerField()),
                ('zip_code', models.CharField(max_length=10)),
                ('neighborhood', models.IntegerField()),
            ],
            options={
                'db_table': 'food_trucks',
                'indexes': [models.Index(fields=['applicant'], name='food_trucks_applica_362ecb_idx'), models.Index(fields=['facility_type'], name='food_trucks_facilit_538c49_idx'), models.Index(fields=['status'], name='food_trucks_status_4de6a0_idx'), models.Index(fields=['latitude', 'longitude'], name='food_trucks_latitud_82f183_idx')],
            },
        ),
    ]
